apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "worker-service.fullname" . }}
  labels:
    {{- include "worker-service.labels" . | nindent 4 }}
data:
  service.conf: |
    # API Service Configuration
    service_name: worker-service
    version: {{ .Chart.AppVersion }}
    {{- if .Values.global }}
    environment: {{ .Values.global.environment }}
    {{- end }}
